// Tiny two-language helper. No i18n library for two languages.
export type Lang = "es" | "en";

let current: Lang = "es";
export const getLang = (): Lang => current;
export const setLang = (l: Lang) => (current = l);
export const toggleLang = (): Lang => (current = current === "es" ? "en" : "es");

type Dict = Record<string, { es: string; en: string }>;

const S: Dict = {
  hud_tokens: { es: "Tokens", en: "Tokens" },
  hud_weapon: { es: "Arma", en: "Weapon" },
  hud_cost: { es: "coste", en: "cost" },
  hint: {
    es: "WASD / flechas mover · ESPACIO atacar · 1·2·3 cambiar arma · E abrir cofre · TAB idioma",
    en: "WASD / arrows move · SPACE attack · 1·2·3 switch weapon · E open chest · TAB language",
  },
  no_tokens: { es: "¡Sin tokens suficientes!", en: "Not enough tokens!" },
  continue: { es: "Continuar", en: "Continue" },

  intro_tag: { es: "Hecho con IA · Demo", en: "Made with AI · Demo" },
  intro_title: { es: "Token Quest", en: "Token Quest" },
  intro_body: {
    es: "Los <b>tokens</b> son tu recurso y tu puntuación. Atacar cuesta tokens; derrotar enemigos y abrir cofres te da más. <b>Gana quien termina con más tokens.</b> Tus armas son <b>modelos de IA</b>: baratas y débiles, o potentes y caras. Elige bien: usar el modelo de frontera para todo arruina tu puntuación.",
    en: "<b>Tokens</b> are your resource and your score. Attacking costs tokens; defeating enemies and opening chests earns more. <b>Whoever ends with the most tokens wins.</b> Your weapons are <b>AI models</b>: cheap and weak, or powerful and expensive. Choose well: using the frontier model for everything wrecks your score.",
  },

  chest_tag: { es: "Cómo lo hizo la IA", en: "How AI made this" },
  chest_title: { es: "Este cofre lo generó un modelo", en: "This chest was generated by a model" },
  chest_body: {
    es: "Cada imagen del juego se generó con IA. Esta es la petición real, el modelo y el coste aproximado que la produjeron:",
    en: "Every image in this game was generated with AI. This is the real prompt, model and approximate cost that produced it:",
  },

  weapon_tag: { es: "Arma = Modelo de IA", en: "Weapon = AI model" },

  victory_tag: { es: "Demo completada", en: "Demo complete" },
  victory_title: { es: "¡Sala despejada!", en: "Room cleared!" },
  victory_body_pre: {
    es: "Terminaste con <b>{tokens} tokens</b>. En el juego completo, ese número es tu puesto en la clasificación. La lección: como con los modelos de IA, <b>el más potente no siempre es la mejor opción</b> — gastar con criterio es lo que gana.",
    en: "You finished with <b>{tokens} tokens</b>. In the full game, that number is your leaderboard rank. The lesson: as with AI models, <b>the most powerful isn't always the right pick</b> — spending deliberately is what wins.",
  },

  meta_model: { es: "Modelo", en: "Model" },
  meta_quality: { es: "Calidad", en: "Quality" },
  meta_cost: { es: "Coste aprox.", en: "Approx. cost" },
};

export function t(key: keyof typeof S): string {
  return S[key]?.[current] ?? String(key);
}
