// Tiny two-language helper. No i18n library for two languages.
export type Lang = "es" | "en";

let current: Lang = "es";
export const getLang = (): Lang => current;
export const setLang = (l: Lang) => (current = l);
export const toggleLang = (): Lang => (current = current === "es" ? "en" : "es");

type Dict = Record<string, { es: string; en: string }>;

const S: Dict = {
  hud_tokens: { es: "Tokens", en: "Tokens" },
  hud_weapon: { es: "Arma", en: "Weapon" },
  hud_cost: { es: "coste", en: "cost" },
  hint: {
    es: "WASD mover · CLIC/ESPACIO atacar · SHIFT esquivar · 1·2·3 arma · E cofre · TAB idioma",
    en: "WASD move · CLICK/SPACE attack · SHIFT dash · 1·2·3 weapon · E chest · TAB language",
  },
  no_tokens: { es: "¡Sin tokens suficientes!", en: "Not enough tokens!" },
  continue: { es: "Continuar", en: "Continue" },

  intro_tag: { es: "Hecho con IA · Demo", en: "Made with AI · Demo" },
  intro_title: { es: "Token Quest", en: "Token Quest" },
  intro_body: {
    es: "Los <b>tokens</b> son tu recurso y tu puntuación. Atacar cuesta tokens; derrotar enemigos y abrir cofres te da más. <b>Gana quien termina con más tokens.</b> Tus armas son <b>modelos de IA</b>: baratas y débiles, o potentes y caras. Elige bien: usar el modelo de frontera para todo arruina tu puntuación.",
    en: "<b>Tokens</b> are your resource and your score. Attacking costs tokens; defeating enemies and opening chests earns more. <b>Whoever ends with the most tokens wins.</b> Your weapons are <b>AI models</b>: cheap and weak, or powerful and expensive. Choose well: using the frontier model for everything wrecks your score.",
  },

  chest_tag: { es: "Cómo lo hizo la IA", en: "How AI made this" },
  chest_title: { es: "Este cofre lo generó un modelo", en: "This chest was generated by a model" },
  chest_body: {
    es: "Cada imagen del juego se generó con IA. Esta es la petición real, el modelo y el coste aproximado que la produjeron:",
    en: "Every image in this game was generated with AI. This is the real prompt, model and approximate cost that produced it:",
  },

  weapon_tag: { es: "Arma = Modelo de IA", en: "Weapon = AI model" },

  victory_tag: { es: "Demo completada", en: "Demo complete" },
  victory_title: { es: "¡Sala despejada!", en: "Room cleared!" },
  victory_body_pre: {
    es: "Terminaste con <b>{tokens} tokens</b>. En el juego completo, ese número es tu puesto en la clasificación. La lección: como con los modelos de IA, <b>el más potente no siempre es la mejor opción</b> — gastar con criterio es lo que gana.",
    en: "You finished with <b>{tokens} tokens</b>. In the full game, that number is your leaderboard rank. The lesson: as with AI models, <b>the most powerful isn't always the right pick</b> — spending deliberately is what wins.",
  },

  meta_model: { es: "Modelo", en: "Model" },
  meta_quality: { es: "Calidad", en: "Quality" },
  meta_cost: { es: "Coste aprox.", en: "Approx. cost" },

  // --- Title ---
  title_tag: { es: "Hecho 100% con IA", en: "100% made with AI" },
  title_tagline: {
    es: "Los tokens son tu puntuación. Tus armas son modelos de IA. Gasta con criterio.",
    en: "Tokens are your score. Your weapons are AI models. Spend deliberately.",
  },
  title_name_label: { es: "Tu nombre", en: "Your name" },
  title_name_ph: { es: "Escribe tu nombre", en: "Enter your name" },
  title_play: { es: "Nueva partida", en: "New game" },
  title_load: { es: "Cargar partida", en: "Load game" },
  title_load_empty: { es: "No hay partida guardada", en: "No saved game" },
  title_leaderboard: { es: "Clasificación", en: "Leaderboard" },
  title_lang: { es: "EN", en: "ES" },
  sound_on: { es: "Sonido ON", en: "Sound ON" },
  sound_off: { es: "Sonido OFF", en: "Sound OFF" },

  // --- Missions / boss ---
  mission_label: { es: "Misión", en: "Mission" },
  mission_guardians: { es: "Derrota a los guardianes", en: "Defeat the guardians" },
  mission_boss: { es: "Derrota al Núcleo corrupto", en: "Defeat the Corrupted Core" },
  boss_appears_tag: { es: "Jefe final", en: "Final boss" },
  boss_appears_title: { es: "El Núcleo despierta", en: "The Core awakens" },
  boss_appears_body: {
    es: "Aguanta mucho daño. Aquí el <b>modelo de frontera</b> por fin merece su coste — pero úsalo solo cuando de verdad hace falta.",
    en: "It soaks huge damage. Here the <b>frontier model</b> finally earns its cost — but use it only when it truly matters.",
  },

  // --- Result / leaderboard ---
  result_victory_tag: { es: "Partida completada", en: "Run complete" },
  result_victory_title: { es: "¡Núcleo destruido!", en: "Core destroyed!" },
  result_defeat_tag: { es: "Fin de la partida", en: "Game over" },
  result_defeat_title: { es: "Te quedaste sin corazones", en: "You ran out of hearts" },
  result_defeat_body: {
    es: "Pero conservaste tus tokens. Reintenta y gasta con más criterio.",
    en: "But you kept your tokens. Retry and spend more deliberately.",
  },
  result_final_tokens: { es: "Tokens finales", en: "Final tokens" },
  result_weapon_usage: { es: "Uso de armas", en: "Weapon usage" },
  result_lesson: {
    es: "Como con los modelos de IA, <b>el más potente no siempre es la mejor opción</b>. La eficiencia gana.",
    en: "As with AI models, <b>the most powerful isn't always the right pick</b>. Efficiency wins.",
  },
  result_submitting: { es: "Enviando puntuación…", en: "Submitting score…" },
  result_submit_ok: { es: "Puntuación enviada a la clasificación", en: "Score submitted to the leaderboard" },
  result_submit_fail: { es: "Sin conexión: puntuación no enviada", en: "Offline: score not submitted" },
  result_play_again: { es: "Jugar otra vez", en: "Play again" },
  result_retry: { es: "Reintentar", en: "Retry" },
  result_menu: { es: "Menú", en: "Menu" },
  made_with_ai_cost: {
    es: "Todo el arte de este juego se generó con IA por unos {cost}.",
    en: "Every image in this game was AI-generated for about {cost}.",
  },

  lb_title: { es: "Clasificación", en: "Leaderboard" },
  lb_loading: { es: "Cargando…", en: "Loading…" },
  lb_empty: { es: "Aún no hay puntuaciones. ¡Sé el primero!", en: "No scores yet. Be the first!" },
  lb_you: { es: "TÚ", en: "YOU" },
  lb_offline: { es: "Clasificación no disponible (sin servidor).", en: "Leaderboard unavailable (no server)." },
};

export function t(key: keyof typeof S): string {
  return S[key]?.[current] ?? String(key);
}
